import jsPDF from 'jspdf';
import type { Student, AttendanceRecord, Holiday } from '@/types';
import { getMonthName } from '@/lib/utils';

export function generatePDFReport(
  student: Student,
  records: AttendanceRecord[],
  month: number,
  year: number,
  stats: { total: number; workingDays: number; present: number; absent: number; percentage: string },
  monthHolidays: Holiday[]
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background
  doc.setFillColor(0, 122, 255);
  doc.rect(0, 0, pageWidth, 45, 'F');

  // App name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('Attendly', 20, 18);

  // Title
  doc.setFontSize(22);
  doc.text('Attendance Report', 20, 34);

  // Student info section
  doc.setTextColor(29, 29, 31);
  doc.setFontSize(14);
  doc.text('Student Information', 20, 62);

  doc.setDrawColor(229, 229, 234);
  doc.line(20, 66, pageWidth - 20, 66);

  doc.setFontSize(11);
  doc.setTextColor(99, 99, 102);

  const infoStartY = 76;
  const lineHeight = 10;
  
  doc.text('Name:', 20, infoStartY);
  doc.setTextColor(29, 29, 31);
  doc.text(student.name, 60, infoStartY);

  doc.setTextColor(99, 99, 102);
  doc.text('Roll No:', 20, infoStartY + lineHeight);
  doc.setTextColor(29, 29, 31);
  doc.text(student.rollNumber, 60, infoStartY + lineHeight);

  if (student.class) {
    doc.setTextColor(99, 99, 102);
    doc.text('Class:', 20, infoStartY + lineHeight * 2);
    doc.setTextColor(29, 29, 31);
    doc.text(student.class, 60, infoStartY + lineHeight * 2);
  }

  // Report period
  doc.setFontSize(14);
  doc.setTextColor(29, 29, 31);
  doc.text(`${getMonthName(month)} ${year}`, 20, infoStartY + lineHeight * 3 + 10);

  doc.setDrawColor(229, 229, 234);
  doc.line(20, infoStartY + lineHeight * 3 + 14, pageWidth - 20, infoStartY + lineHeight * 3 + 14);

  // Summary cards
  const summaryY = infoStartY + lineHeight * 3 + 28;
  const cardWidth = (pageWidth - 40 - (4 * 4)) / 5; // 5 cards fit
  
  const cards = [
    { label: 'Calendar', value: stats.total.toString(), color: [0, 122, 255] },
    { label: 'Working', value: stats.workingDays.toString(), color: [0, 122, 255] },
    { label: 'Present', value: stats.present.toString(), color: [52, 199, 89] },
    { label: 'Absent', value: stats.absent.toString(), color: [255, 59, 48] },
    { label: 'Percentage', value: `${stats.percentage}%`, color: [0, 122, 255] },
  ];

  cards.forEach((card, i) => {
    const x = 20 + i * (cardWidth + 4);
    doc.setFillColor(245, 245, 247);
    doc.roundedRect(x, summaryY, cardWidth, 35, 4, 4, 'F');

    doc.setFontSize(14);
    doc.setTextColor(card.color[0], card.color[1], card.color[2]);
    doc.text(card.value, x + cardWidth / 2, summaryY + 16, { align: 'center' });

    doc.setFontSize(8);
    doc.setTextColor(142, 142, 147);
    doc.text(card.label, x + cardWidth / 2, summaryY + 27, { align: 'center' });
  });

  let currentY = summaryY + 50;

  // Holidays Section
  if (monthHolidays.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(29, 29, 31);
    doc.text('Holidays in Month', 20, currentY);
    
    doc.setFontSize(9);
    let holidayY = currentY + 8;
    monthHolidays.forEach((h) => {
      const hd = new Date(h.date + 'T00:00:00');
      doc.setTextColor(255, 149, 0); // Orange
      doc.text(`${hd.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}: ${h.title}`, 20, holidayY);
      holidayY += 6;
    });

    currentY = holidayY + 10;
  }

  // Daily records table
  const tableY = currentY;
  doc.setFontSize(14);
  doc.setTextColor(29, 29, 31);
  doc.text('Daily Records', 20, tableY);

  // Table header
  doc.setFillColor(245, 245, 247);
  doc.rect(20, tableY + 5, pageWidth - 40, 10, 'F');
  doc.setFontSize(9);
  doc.setTextColor(142, 142, 147);
  doc.text('Date', 25, tableY + 12);
  doc.text('Day', 80, tableY + 12);
  doc.text('Status', pageWidth - 50, tableY + 12);

  // Table rows
  let rowY = tableY + 20;
  doc.setFontSize(9);
  
  records.forEach((record, index) => {
    if (rowY > 270) {
      doc.addPage();
      rowY = 20;
    }

    if (index % 2 === 0) {
      doc.setFillColor(250, 250, 252);
      doc.rect(20, rowY - 5, pageWidth - 40, 9, 'F');
    }

    const date = new Date(record.date + 'T00:00:00');
    doc.setTextColor(29, 29, 31);
    doc.text(date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), 25, rowY);
    doc.text(date.toLocaleDateString('en-US', { weekday: 'short' }), 80, rowY);

    if (record.status === 'present') {
      doc.setTextColor(52, 199, 89);
      doc.text('Present', pageWidth - 50, rowY);
    } else {
      doc.setTextColor(255, 59, 48);
      doc.text('Absent', pageWidth - 50, rowY);
    }

    rowY += 9;
  });

  // Footer
  const lastPage = doc.getNumberOfPages();
  for (let i = 1; i <= lastPage; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(174, 174, 178);
    doc.text(
      `Generated by Attendly on ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  doc.save(`${student.name}-attendance-${getMonthName(month)}-${year}.pdf`);
}
